---
  ###########################
  ###########################
  ## Pull request testing ##
  ###########################
  ###########################
  name: Validate pull request
  
  # Documentation:
  # - Workflow: https://help.github.com/en/articles/workflow-syntax-for-github-actions
  # - SuperLinter: https://github.com/github/super-linter
  # - Link validation: https://github.com/remarkjs/remark-validate-links
  
  ######################################################
  # Start the job on a pull request to the main branch #
  ######################################################
  on: pull_request

  permissions:
    contents: read
    statuses: write
  
  ###############
  # Set the Job #
  ###############
  jobs:
    validate:
      uses: commerce-docs/commerce-testing/.github/workflows/validate-pr_job.yml@ds_pr-test-wf
